-- Схема ceramic.
-- Пользователи/сессии - общие с porcelain_archive, см. member/session.
-- Документы/страницы - тоже общие с porcelain_archive (document/branch/page).
-- Обратная связь - тоже общая с porcelain_archive (message/important_feedback).
-- Заводы (factories) и подписчики (subscribers) удалены как отдельная фича.
